version: "3.7"
services:
  nohackgenda:
    image: nohackgenda
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      # - "CERTIFICATE_C="
      # - "CERTIFICATE_ST="
      # - "CERTIFICATE_L="
      - "CERTIFICATE_O=nohackgenda"
      # - "CERTIFICATE_CN="
      - "PORT_HTTP=8080"
      - "PORT_HTTPS=8081"
    ports:
      - 8080:8080 # should be the same
      - 8081:8081 # should be the same
    restart: on-failure:3
    read_only: true
    volumes:
        - "$PWD/data:/src/data"
    tmpfs:
        - /src/keys
